name: "V0 to V1 Migration Issue"
title: "Issue with V1 Migration: "
description: >
  Report an issue with the V0 to V1 migration.
assignees:
  - maintainers

labels:
- v1-migration-issue

body:

- type: dropdown
  attributes:
    label: Language
    description: Programming Language used with AWS CDK
    options:
      - TypeScript/JavaScript
      - Python
      - Go
  validations:
    required: true

- type: input
  attributes:
    label: Version of aws-cdk-lib
    description: >
      AWS CDK Library version used
  validations:
    required: true

- type: input
  attributes:
    label: Version of aws-cdk
    description: >
      AWS CDK CLI/Toolkit version used
  validations:
    required: true

- type: input
  attributes:
    label: Original version of @alma-cdk/project
    description: >
      The v0 version used before migration to v1
  validations:
    required: true

- type: textarea
  attributes:
    label: Explain the problem
    description: Do not disclose any sensitive information (including AWS Account IDs)!
    placeholder: Tell us what happened. Do not disclose any sensitive information (including AWS Account IDs)!
  validations:
    required: true
